- name: Hello World Sample
  roles:
    - Juniper.junos  
    
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: run show version on remote devices
      junipernetworks.junos.junos_command:
        commands: show version
