---

- name: Network Getting Started First Playbook
  connection: local
  gather_facts: false
  hosts: juniper
  roles:
    - juniper.junos
  vars:
    ansible_ssh_user: jnpr
  tasks:

    - name: run show version on remote devices
      juniper_junos_command:
        commands:
          - show version
          - show route
        provider:
          port: 22
